# Generated by Django 3.1.4 on 2022-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdtime'],
            },
        ),
    ]
