# Generated by Django 3.1.4 on 2022-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
