# Generated by Django 3.2.4 on 2021-12-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('content', models.TextField(max_length=1000)),
                ('pic', models.CharField(max_length=200)),
                ('createdtime', models.TimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cat.cat')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'ordering': ['-createdtime'],
            },
        ),
    ]
