# Generated by Django 3.2.4 on 2022-01-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
