# Generated by Django 3.1.4 on 2022-04-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moments', '0001_initial'),
        ('user', '0001_initial'),
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMoments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moments.moments')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='LikeCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cat.cat')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
