# Generated by Django 3.2.4 on 2021-12-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CatLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=200)),
                ('catpic', models.CharField(max_length=200)),
                ('catlike', models.IntegerField()),
                ('catcolor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cat.catcolor')),
                ('catlocation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cat.catlocation')),
            ],
            options={
                'ordering': ['catlike'],
            },
        ),
    ]
