# Generated by Django 3.2.4 on 2022-01-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-catlike']},
        ),
    ]
