# Generated by Django 3.2.4 on 2021-12-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid', models.CharField(max_length=200)),
                ('avatarurl', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('gender', models.IntegerField(blank=True)),
                ('nickname', models.CharField(max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
