# Generated by Django 3.2.4 on 2021-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=200)),
                ('CatColor', models.CharField(max_length=200)),
                ('CatLocation', models.CharField(max_length=200)),
            ],
        ),
    ]
