# Generated by Django 3.2.4 on 2021-12-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColorName', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='CatColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testurl.catcolor'),
        ),
    ]
