# Generated by Django 3.2.4 on 2021-12-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0002_auto_20211227_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='CatColor',
            field=models.CharField(max_length=200),
        ),
    ]
