# Generated by Django 3.2.4 on 2021-12-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0003_alter_cat_catcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='CatColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testurl.catcolor'),
        ),
    ]
