# Generated by Django 3.2.4 on 2021-12-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testurl', '0004_alter_cat_catcolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='CatColor',
        ),
    ]
